name: AdvancedReportSystem
version: 1.6.0
website: skysetups.com
main: com.example.advancedreportsystem.AdvancedReportSystem
author: wlsonyt
description: Gelişmiş rapor sistemi
api-version: 1.20
commands:
  report:
    description: Rapor menüsünü açar
    usage: /report
  reportadmin:
    description: Rapor yönetim komutları
    usage: /reportadmin [ban/kick/warn] [oyuncu] [sebep]
permissions:
  reportsystem.admin:
    description: Rapor sistem yönetimi izni
    default: op